voxel_size: 0.05  # Size of each voxel in the VoxelGrid (in mm)
object_filenames:
  - part11
  - part13
  - part23

# The center of the larger circle of part11 is the origin of the assembly.
# part frame based on assembly frame (a_i)
assembly_calibrations:
  part11:
    [[1,0,0,-4],
     [0,1,0,0],
     [0,0,1,-4],
     [0,0,0,1]]
  part13:
    [[1,0,0,-3],
     [0,1,0,32],
     [0,0,1,-3],
     [0,0,0,1]]
  part23: # mat[0] @ mat[1]
      [[[0,1,0,0],
        [1,0,0,0],
        [0,0,1,0],
        [0,0,0,1]],
       [[1,0,0,1.683],
        [0,1,0,-3.37],
        [0,0,1,-3.37],
        [0,0,0,1]]]
# part frame based on world frame (w_i = w_a @ a_i)
transform_matrix:
  H_wc: # Apply rotation
    [[1,0,0,0], # in mm
     [0,1,0,0],
     [0,0,1,950], # z < sdd
     [0,0,0,1]]
  H_ca:
    [[1,0,0,0],
     [0,1,0,-22.5],
     [0,0,1,0],
     [0,0,0,1]]